### PR TITLE
SSKW 54 - Table organism

### LINKED ISSUE #54: SSKW - Table organism
## Checklist ✅

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/Sphinx-Society/kaizen-web-client/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Create a table organism to use in the desktop principal menu in all roles.

## Requirements 🌈

- It must follow the design system
- It mus have tests and documentation

## Motivation 🔦

This organism will help the profiles to manage the data in their principal views.

### PR DESCRIPTION
**Pull request by omarefg**
## Checklist ✅

- [x] I have followed the [contributor guideline](https://github.com/Sphinx-Society/kaizen-web-client/blob/master/CONTRIBUTING.md)
- [ ] Tests are included
- [x] Documentation is changed or added
- [x] Related issue has been created
- [x] Commits messages follows [commit guideline](https://github.com/Sphinx-Society/kaizen-web-client/blob/master/CONTRIBUTING.md/#Commits)

resolves #54

### CODE REVIEW

**Comment by omarefg** [comment]
Guys here is the table component, it is functional for you to start using it but it in the views, it do not have tests yet, as we agreed the tests are going to be done this week and deployed in a new PR.

It's documented.

It's also prepared to receive the cards or `mobileRow` as is called the prop but the cards are not done yet. I think is better to make them on a new branch.

**Comment by omarefg** [comment]
It is kind of a complex component, all changed files are related to it or to a little dependency of it.

**Comment by jhnemogap** [comment]
And the logo? o loader? 
For this time, I'll pretend I didn't see, :rofl: . To the next "hay tabla". I don't behave seriously in a PR

**Comment by omarefg** [comment]
The Logo and Loader components are actually the same, it was a little dependency of the table to represent the loading variant, but It did not make sense to do it only for the Table component instead of that I made an abstraction so it could be used anywhere  else in the project. You're right, it could be made in another issue and PR, but the lack of logic inside was perfect for including it here. Lets say we agree to disagree on this one :grin:

**Pull request merged**
